%% project 7a
clear all;close all;clc;
syms x val
integral = int(sin(x),0,pi);% for f(x)=c*sin(x)
c = 1/integral
Fx1 = int(c*sin(x)) + val;
t = subs(Fx1,x,0);
value = solve(t);
Fx = subs(Fx1,val,value) %find F(X)
mean = int(x*c*sin(x),0,pi) % find mean 
%mean_1=int(x^2*c*sin(x),0,pi)
variance = int((x-mean)^2*c*sin(x),0,pi) %find variance
%variance_1

%% project 7b
g = finverse(Fx);
% for N=10, samples=10
yy1 = zeros(0);
xx1 = zeros(0);
for i =1:10;
    yy1(i) = rand();
    xx1(i) = subs(g,x,yy1(i));
end;
figure(1);
cdfplot(xx1); hold on; % the empirical distribution generated by samples
ezplot(Fx,[0,pi]); % the true underlying distribution function
% for N=100, samples=100
xx2 = zeros(0);
yy2 = zeros(0);
for i =1:100;
    yy2(i) = rand();
    xx2(i) = subs(g,x,yy2(i));
end;
figure(2);
cdfplot(xx2); hold on;
ezplot(Fx,[0,pi]);
% for N=1000, samples=1000
yy3 = zeros(0);
xx3 = zeros(0);
for i =1:1000;
    yy3(i) = rand();
    xx3(i) = subs(g,x,yy3(i));
end;
figure(3);
cdfplot(xx3); hold on;
ezplot(Fx,[0,pi]);

%% project 7c
% for N=100
xx2 = zeros(0);
yy2 = zeros(0);
for i =1:100;
    yy2(i) = rand();
    xx2(i) = subs(g,x,yy2(i));% sample varience s^2
end;

m  = sum(xx2)/100 % the sample mean, m
mse = variance/100 % MSE of mean estimate
msec = var(xx2)/100 % MSE of mean estimate based on sample variance

%% project 7d
% for N=100
sample = zeros();
 for i=1:50 %generate M bootstrap samples, for M=50
    boot = randi(100,1);
    sample(i) = xx2(boot);
 end;
 mean_of_b_sample = sum(sample)/50 %mean for bootstrap sample,m=50
 var_of_b_sample = var(sample) %variance for bootstrap sample,m=50
 
 %% project 7e
 varofsample = zeros();
array = zeros();
for m=1:1000
    sample = zeros();
        for i=1:50
            boot = randi(100,1);
            sample(i) = xx2(boot);
        end;
    varofsample(m) = var(sample);
    array(m) = (varofsample(m) - 0.5365)^2;
end;
mse_estimate_sample = sum(array)/1000